apiVersion: v1
kind: Service
metadata:
  labels:
    app: scraper
  name: scraper-loadbalancer-service
  namespace: libp2p-dht-scrape-aas
spec:
  selector:
    app: scraper
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  